version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: contact.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root:
  level: ERROR
  handlers: [file]

loggers:
  freshdesk_contact:
    level: DEBUG
    handlers: [file]
    propagate: no
